spring.application.name=3.2-PracticaApiSecurity

# Configs de seguridad en la BBDD
spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}

# Configs de la BBDD
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

