spring.application.name=2-BackendSimple
spring.datasource.url=jdbc:postgresql://localhost:5432/1.PrimerConexionConApi
spring.datasource.username=postgres
spring.datasource.password=290703
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true