spring.application.name=3.1-ApiConOAuth2

# Configs de Seguridad
spring.security.user.name = ${SS_USER}
spring.security.user.password= = ${SS_PASSWORD}
# Para este ejemplo no usamos una base de datos por lo que el rol se lo mando aca
spring.security.user.roles = ${ROLE}

# Configuracion para GitHub
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

#Configuraciones de OAuth con Google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

